---
# tasks file for nginx
- name: Copy upstart file
  copy: src=nginx-upstart.conf dest=/etc/init/nginx.conf owner=root group=root mode=0644

- name: Install nginx
  apt: name=nginx state=latest

- name: Copy nginx configuration for roshi-server
  copy: src=default  dest=/etc/nginx/sites-available/default
  notify: restart nginx

- meta: flush_handlers

- name: Enable service
  service: name=nginx enabled=yes state=started
