---
# Install, Build and deploy Roshi-server
- name: install and configure golang
  hosts: build
  remote_user: ubuntu
  become: yes
  roles:
   - golang

- name: build roshi server
  hosts: build
  remote_user: ubuntu
  become: yes
  vars_files:
    - playbooks/vars/main.yml
  tasks:
    - include: playbooks/buildtasks.yml

- name: copy artifact to s3 bucket
  hosts: local
  vars_files:
    - playbooks/vars/main.yml
  tasks:
    - include: playbooks/copyartifacts.yml
