---
# tasks file for building and packing roshi
- name: Install needed packages
  apt: name={{ item }} update_cache=yes state=present
  with_items: "{{ packages }}"

- name: Copy build script
  copy: src=scripts/build-roshi.sh dest=/usr/local/bin/build-roshi.sh owner=root group=root mode=0755

- name: Create build
  shell: /usr/local/bin/build-roshi.sh

- name: Download package
  fetch: src="{{ roshi_pkg }}/{{ roshi_package }}"  dest={{ local_directory }} flat=yes
